version: '3'

services:
    server:
        build: ./server
        stdin_open: true
        tty: true
        volumes: 
            - ./server:/home/node/app/server
            - servermodules:/home/node/app/server/node_modules
        ports:
            - 4001:4001
    client:
        build: ./client
        stdin_open: true
        tty: true
        volumes:
            - ./client:/home/node/app/client
            - clientmodules:/home/node/app/client/node_modules
        ports:
            - 4000:4000
        depends_on:
            - server
              
volumes: 
  servermodules:
  clientmodules:
